### ISSUE TITLE
New Issue

### ISSUE THREAD

**Issue by OscarJuma** [strikerst09/Project1#7]
What questions do we all have? What is the "cool name" of our project/group?

**Comment by strikerst09** [comment]
## User Stories

How much wood would a woodchuck chuck if a woodchuck could chuck wood?

##Acceptance Criteria

-[] all of it
-[] less than all of it but more than none
-[] none of it

**Comment by rebake44** [comment]
How many Lowe's could Rob Lowe rob if Rob Lowe could rob Lowe's?

**Comment by rebake44** [comment]
Just listing things as I think of them:
HTML framework
API for News/Headlines
API for Top Song
API for Top Movie
javascript for each API
Firebase for each API
CSS for HTML

**Comment by rebake44** [comment]
API for Celebrity Birthdates
